script = "foxhist"
desc   = "compute statistic for firefox browser's history and print it sorted"
examples = [
	 ["foxhist","shows result based on different urls."],
	 ["foxhist root","shows result based on matched root urls."],
	 ["foxhist cap=2 db=~/.mozilla/firefox/somestrangepath/places.sqlite", "shows pages with visiting count above 2"]
]
